name: Traveling Consultant Dude
favicon: null
layout_spectrum: 0.37954782391898334
typography_spectrum: 0.3725569259840995
title: Traveling Consultant Dude
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06075076572597027
  lightness: 0.33915758691728115
  saturation: 0.01930273463949561
  rhythmicContrast: 0.11501944973133504
purpose: []
