name: Traveling Consultant Dude
favicon: null
layout_spectrum: 0.34226
typography_spectrum: 0.3725569259840995
title: Traveling Consultant Dude
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
